plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.91'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories.clear()
repositories {
    // Mirror Maven
    maven {
        url = "https://neoforged.forgecdn.net/releases"
    }
    maven {
        url = "https://neoforged.forgecdn.net/mojang-meta"
    }

    maven {
        url = "https://maven.minecraftforge.net/"
    }
    maven {
        url = "https://libraries.minecraft.net/"
    }

    mavenLocal()

    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url "https://repo.spongepowered.org/repository/maven-public/"
    }
    maven {
        url "https://maven.architectury.dev/"
    }
    maven {
        url "https://maven.latvian.dev/releases"
    }
    maven {
        url = 'https://maven.blamejared.com'
    }
    maven {
        url "https://maven.blazing-coop.net/releases"
    }
    maven {
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    flatDir {
        dir 'libs'
    }
}

base {
    archivesName = "${mod_id}"
}

legacyForge {
    version = project.minecraft_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            gameDirectory = project.file('run/server')
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file('run/gametest')
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            gameDirectory = project.file('run/data')
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG

            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'mixin.debug.export', 'true'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

dependencies {

    // Embeddium
    modImplementation("curse.maven:embeddium-908741:5681725")

    // Better Brightness Slider
    modImplementation("curse.maven:better-brightness-slider-685037:4656287")

/*    // 突变生物
    modImplementation("curse.maven:mutant-monsters-852665:5107399")

    // Puzzles Lib
    modImplementation("curse.maven:puzzles-lib-495476:6918565")*/

/*    // 血族传说
    modImplementation("curse.maven:vampirism-become-a-vampire-233029:6289561")

    // Guide-API
    modImplementation("curse.maven:guide-api-village-and-pillage-380771:4799858")*/

/*    // 冰火传说
    modImplementation("curse.maven:ice-and-fire-dragons-264231:5633453")

    // 暮色森林
    modImplementation("curse.maven:the-twilight-forest-227639:5468648")

    // Citadel
    modImplementation("curse.maven:citadel-331936:6702068")

    // 祸乱鬼魅Forge版
    modImplementation("curse.maven:bosses-of-mass-destruction-forge-941573:5067728")

    // CERBON's API
    modImplementation("curse.maven:cerbons-api-955605:5050080")*/

    // Cloth Config API
    modImplementation("curse.maven:cloth-config-348521:5729105")

/*     // 天神剑技
    modImplementation("curse.maven:celestisynth-872712:6900952")*/

/*    // Alex的洞穴
    modImplementation("curse.maven:alexs-caves-924854:5848216")*/

/*    // Alex的生物
    modImplementation("curse.maven:alexs-mobs-426558:5698791")*/

    // 属性修复
    modImplementation("curse.maven:attributefix-280510:4911084")

/*    // 血肉重铸
    modImplementation("curse.maven:biomancy-492939:5886758")*/

/*    // PlayerAnimator
    modImplementation("curse.maven:playeranimator-658587:4587214")*/

/*    // GeckoLib
    modImplementation("curse.maven:geckolib-388172:7025129")*/

    // 试验假人
    modImplementation("curse.maven:mmmmmmmmmmmm-225738:6860192")

    // Moonlight Lib
    modImplementation("curse.maven:selene-499980:7027387")

    // JEI物品管理器
    modImplementation("curse.maven:jei-238222:4712868")
    modImplementation("curse.maven:just-enough-resources-jer-240630:5057220")

    // 玉
    modImplementation("maven.modrinth:jade:11.13.1+forge")

/*    // 灾变
    modImplementation("curse.maven:lendercataclysm-551586:6729683")
    modImplementation("curse.maven:lionfish-api-1001614:5922047")*/

/*    // Curios
    modImplementation("curse.maven:curios-309927:6418456")*/

    // kubejs
    modImplementation("dev.architectury:architectury-forge:${architectury_version}")
    modImplementation("dev.latvian.mods:rhino-forge:${rhino_version}")
    modImplementation("dev.latvian.mods:kubejs-forge:${kubejs_version}")

    // 怪物大乱斗
//    modImplementation("io.github.flemmli97:mobbattle:${minecraft_version}-2.5.3-${mod_loader}")


    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0"))

    implementation "org.jetbrains:annotations:17.0.0"

//    modRuntimeOnly("curse.maven:curtain-845348:4704521")
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            author_address         : author_address
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
